import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Mascot from "./components/Mascot.jsx";
import { SpeechProvider } from './components/SpeechContext.jsx'
import UserProvider from "./components/User";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Craft Connect",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className ={inter.className}>
      <UserProvider>
      <SpeechProvider>
          <Navbar />
          <Mascot /> 
          {children}
        </SpeechProvider>
        </UserProvider>
        </body>
    </html>
  )
}